### ISSUE TITLE
[SR-4758] SE-0142: derived protocol that restricts associatedtype should be allowed as a variable type

### ISSUE THREAD

**Issue by nsalmoria** [apple/swift#47335]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4758      |
   |Radar             | rdar://problem/58438127         |
   |Original Reporter | @nsalmoria      |
   |Type              | Improvement    |

<details>
  <summary>Environment</summary>

Swift Development Snapshot 2017-04-24 (a)  
Xcode 8.3.2  
macOS Sierra 10.12.4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Compiler    |
   |Labels            | Improvement        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 992bea1bd30120d41ee308b8b85d8e1e

  </details>

**is duplicated by**:  
* [SR-7336](https://bugs.swift.org/browse/SR-7336) Protocol with same-type constraint on associated type "can only be used as generic constraint"  
* [SR-9260](https://bugs.swift.org/browse/SR-9260) Allow protocol types with fully specified associated types in all type positions (function arguments etc.)  
* [SR-9501](https://bugs.swift.org/browse/SR-9501) Subclass existential with predefined associated type witness should be supported as existential  

**relates to**:  
* [SR-13502](https://bugs.swift.org/browse/SR-13502) Have to place empty generics when using protocol + where cause in function  

**Issue Description:**

With the implementation of [SE-0142](https://github.com/apple/swift-evolution/blob/master/proposals/0142-associated-types-constraints.md), it is now possible to force the associated types of a derived protocol to be of a specific type.

Arguably, when all the associated types are restricted, it should be possible to use the derived protocol as the type of a variable. However, the compiler still rejects the code.

Example:

``` java
protocol A {
    associatedtype B
}

protocol C: A where B == Int {

}

struct D {
    var c: C  // error: Protocol 'C' can only be used as a generic constraint because it has Self or associated type requirements
}
```

In the example above, protocol C has no degrees of freedom so it shouldn't need to be restricted to generic code.

**Comment by slavapestov** [comment]
This is implemented in Swift 5.7 as part of SE-0309.

**Comment by lutes1** [comment]
As of **Swift 5.10**, this issue is still not resolved, [SE-0309](https://swiftlang.github.io/swift-evolution/#?proposal=SE-0309) only masks the issue but does not resolve it. We still have to use `any` which comes with its own limitations.

Considering the example described initially in this issue, the protocol `C` should behave as any other protocol without `Self` or `associatedType` requirements, which is not currently the case.

Updated example:

```
protocol A {
    associatedtype B
    var item: B { get }
}

protocol C: A where B == Int { 

}

struct D {
    var c: C  // error: Use of protocol 'C' as a type must be written 'any C'
}
```

The expected behaviour is that the 'C' protocol should not behave any different than
```

protocol E {
    var item: Int { get }
}
```

(Please let me know if I'm missing something)

**Comment by AnthonyLatsis** [comment]
Requiring `any` syntax here is [intentional](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0335-existential-any.md#source-compatibility). `any` was initially enforced under the exact same legacy criteria that protocols with "Self or associated type" requirements were once prohibited in existential types pre SE-0309. `where B == Int` never counted to whether a protocol has "Self or associated type" requirements. We are moving toward obsoleting this old and misleading term and the code supporting it with a world where `any` is always required on existentials, or, just maybe, something different. Changes to the definition of a "Self or associated type" requirement would take us a step back and aggravate a likely future migration at this point.

**Comment by lutes1** [comment]
Thanks for response,

I get why `any` is mandatory here and it makes sense — it indeed helps a lot in dealing with PATs. However, the use case here is different. We should be able to specialize a protocol to get rid of any abstraction defined by its parent as it is not relevant at a lower abstraction level.

Is there any other way to specialize the protocol `C` that would make it equivalent to protocol `E` from a client stand point?

An option that comes to mind _(example below)_ is to use a primary associated type on `A` and just specify `Int` as a primary associated type at `C`'s declaration but the result is the same: `C` is still considered abstract over `B` which doesn't really make sense as we have defined `B` to be `Int`.


```
protocol A<B> {
    associatedtype B
    var item: B { get }
}

protocol C: A<Int> {
    var item: Int { get }
}

struct D {
    var c: C  // error: Use of protocol 'C' as a type must be written 'any C'
}
```

Or even simpler, the basic example — but still the same issue.

```
protocol A {
    associatedtype B
    var item: B { get }
}

protocol C: A {
    var item: Int { get }
}

struct D {
    var c: C  // error: Use of protocol 'C' as a type must be written 'any C'
}

```

**Comment by AnthonyLatsis** [comment]
`C` is already equivalent to `E` in that the type of `item` is specialized and you can access that property. `any` is merely a new syntax for protocol types — it doesn’t imply that `C` is more abstract than `E`. You can spell `E` using `any` too. The reason that mandatory `any` syntax for protocols like `E` was gated behind an upcoming feature option, and not enabled by default, is that it’s a source-breaking change.
