### ISSUE TITLE
[SR-13591] REPL is not working on swift-5.3-RELEASE (Windows)

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56026]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13591      |
   |Radar             | None         |
   |Original Reporter | gazsiazasz (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

`Windows 10 - swift-5.3-RELEASE`

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       |     |
   |Labels            | Bug, Windows        |
   |Assignee          | @compnerd      |
   |Priority          | Medium      |

   md5: 34aed1a92808f2bdb31c9273d970f787

  </details>

**is blocked by**:  
* https://github.com/apple/llvm-project/issues/4418

**is duplicated by**:  
* https://github.com/apple/llvm-project/issues/4328

**Issue Description:**

When I issue the command swift it should launch the REPL. But instead of that it gives back the prompt immediately.

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.4
** Copyright (c) 2020 Microsoft Corporation
********************************************************************** 
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>swift

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>swift --version
compnerd.org Swift version 5.3 (swift-5.3-RELEASE)
Target: x86_64-unknown-windows-msvc

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>
```

**Comment by compnerd** [comment]
I could use a bit of help testing this, I think that we are in a slightly better position now with the REPL, though it still needs further work.  In the meantime, if someone else can test and verify that that this seems to work better with the [2023-04-11-a snapshot](https://artprodeus21.artifacts.visualstudio.com/A8fd008a0-56bc-482c-ba46-67f9425510be/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NvbXBuZXJkL3Byb2plY3RJZC8zMTMzZDZhYi04MGE4LTQ5OTYtYWM0Zi0wM2RmMjVjZDMyMjQvYnVpbGRJZC82MTc3NC9hcnRpZmFjdE5hbWUvaW5zdGFsbGVyLWFtZDY00/content?format=file&subPath=%2Finstaller.exe) it would be useful.  In order to get this to actually work the REPL needs to be invoked with some additional parameters, namely `-L...` where the value is the location of the installed runtime (defaults to `%Program Files%\swift\runtime-development\usr\bin`).  This is slightly confusing and will need to be resolved, but getting some preliminary testing on this would be helpful to ensure that the various issues are identified.

```cmd
S:\>swift repl "-LS:\Program\ Files\swift\runtime-development\usr\bin"
Welcome to Swift version 5.9-dev (LLVM 91080e65df791d6, Swift a35e5ab3295f464).
Type :help for assistance.
1> import Foundation
2> ProcessInfo.processInfo
$R0: Foundation.ProcessInfo = {
  Foundation.NSObject = {}
  processName = "repl_swift.exe"
  $__lazy_storage_$__operatingSystemVersionString = nil
  _processorCount = 1
  _activeProcessorCount = 20
  _physicalMemory = 0
}
3>
```

You will need to ensure that python is in your path of course but that has always been a requirement.

**Comment by lxbndr** [comment]
It works with 2023-04-11 snapthot (`LLVM 8277d73ee656251, Swift 4de53fc2e7cee4d`). Thanks for note about extra slash in `Program \Files`).
Tried `ProcessInfo.processInfo` and `RunLoop.current` and got a valid output.

**Comment by compnerd** [comment]
https://github.com/apple/llvm-project/pull/6927 should be the last bit that I think that is missing.  With that in place, I can now launch the REPL without any additional parameters (`swift repl`).

**Comment by compnerd** [comment]
The changes have been merged and should be part of the next snapshot.

**Comment by svanimpe** [comment]
Should this be working in 5.9? If I try to run `swift repl`, I just get an error saying **python39.dll** is missing.

I have Python 3.10 installed, as per the instructions on https://www.swift.org/install/windows/#installation-via-windows-package-manager

**Comment by Keithcat1** [comment]
I just got the REPL working with [https://github.com/pwsacademy/swift-setup/blob/main/platforms/windows/README.md](These instructions). It can evaluate 2+2, for example. Running files with `swift h.swift` now fail with errors about JIT session: symbols not found and then abunch of mangled symbol names.
I'm using the Swift installer from [https://github.com/thebrowsercompany/swift-build/releases](here), which may work better than the default.

**Comment by compnerd** [comment]
`swift h.swift` is going to fail for now. You might be able to use `swift -O h.swift` for the time being. There is still more work that needs to be done on the interpreter.

**Comment by Keithcat1** [comment]
Adding -O allows a simple h`print("hello world!")` to compile, but anything that tries to import foundation still can't materialize symbols. I'll just compile. When is the REPL going to not require python39.dll? This seems like the main blocker and means I need 2 installations of Python on my Windows computer.
