### ISSUE TITLE
[SR-15872] [() -> Void] allocates when appending a closure

### ISSUE THREAD

**Issue by fabianfett** [apple/swift#58137]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15872      |
   |Radar             | None         |
   |Original Reporter | @fabianfett      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

I could see this repro in 5.5, 5.6 and main on macOS as well as on ubuntu focal.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2d38e44ce0ef10abd98ea6c6ba19718a

  </details>

**Issue Description:**

I discovered a very interesting case today: Given the following code, I see an allocation for every call to `append`.

``` swift
var array = [() -> Void>]()
array.reserveCapacity(1000)

var counter = 0
var closure = {
    counter += 1
}

for _ in 0..<1000 {
    array.append(closure)
}
```

Whereas if I wrap my closure in a struct, I don't see an allocation for every `append` in:

``` swift
struct Foo {
    var closure: () -> Void
}

var array = Array<Foo>()
array.reserveCapacity(1000)

var counter = 0
var closure = {
    counter += 1
}

for _ in 0..<1000 {
    array.append(Foo(closure: closure))
}
```

I expect array not to allocate when I append a closure.

**Comment by weissi** [comment]
still unfixed in latest snapshots

```
$ pbpaste | swiftc -enforce-exclusivity=unchecked -O  -; sudo dtrace -n 'pid$target::malloc_zone_malloc:entry { @ = count(); }' -c ./main
dtrace: system integrity protection is on, some features will not be available
dtrace: description 'pid$target::malloc_zone_malloc:entry ' matched 1 probe
dtrace: pid 41958 has exited

           100009
```

**Comment by jckarter** [comment]
`Array` being a fully generic type uses a different representation for `() -> Void` than a variable of concrete type like `let closure: () -> Void`. Because `closure` is a global variable we cannot optimize its representation to avoid the thunk when copying a value from the variable into the array. Changing `closure` into a standalone function as in https://github.com/apple/swift/issues/58137#issuecomment-1108472617 is one way to avoid this. Using a `struct` to contain the closures as noted in the OP is another.
