### ISSUE TITLE
"Good first issue" tag

### ISSUE THREAD

**Issue by AustinConlon** [apple/swift#58541]
A suggestion I have for this repo is I think it would be nice to have a "good first issue" tag applied to relevant issues.

**Comment by CodaFi** [comment]
Thanks for the suggestion, a big +1. We have StarterBug and StarterProposal migrated over from JIRA, but those labels have a murky history and were applied on a best-effort basis. So some of the StarterBugs are in fact... well they require domain knowledge. And a StarterProposal is a tall order these days considering it requires an implementation.

**Comment by AustinConlon** [comment]
Ah, missed those, I'm used to the default phrasing in GitHub labels. Thanks!

**Comment by xedin** [comment]
+1, we just need to migrate existing `StarterBug` over to use `Good first issue` and comb through the issues to mark some more as such.

**Comment by Rajveer100** [comment]
Hi there, this is Rajveer here, before you read below, you can checkout my profile for detailed info about my personal journey, which would help you in giving a brief idea about me, because I completely understand many random people are knew and it's hard to figure out an in-person overview about someone...
[https://github.com/Rajveer100](url) 
(Please do checkout the Personal-CV repo for my resume, for detailed info apart from projects...)

[Now coming to my best try to start contributing to the repo:]

I am actually new to contributing to Swift and hence needed help regarding the same, after going through the starter guide about how to start contributing (via documentation...)

I followed the starter steps as mentioned here: 
[https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md](url)

Now I need just a little guidance for this particular "Starter Bug Issue" as a first PR, to get the hand or touch in contributing to the repo...

Thanks,
[Appreciate your reply]

**Comment by AnthonyLatsis** [comment]
Duplicate of #61467
