### ISSUE TITLE
There should be record update syntax

### ISSUE THREAD

**Issue by lovely-error** [apple/swift#58607]
There exist a couple of computer language out there that do have feature commonly recognised as 'record update syntax'. Rust have it, Haskell have it, f# have it as well. It should also be in swift!

**Comment by CodaFi** [comment]
Record update syntax is necessary when you need to recreate a value with a subset of its fields altered. Swift's syntax for this is plain mutation, which has the same semantics as each mutating access creates a semantic copy of the original value. Where this falls apart is when you have a struct-of-lets and a memberwise initializer, which is an active design choice that I would argue is a huge anti-pattern.

**Comment by grynspan** [comment]
Can you give an example of what this feature might look like in the language?

**Comment by AnthonyLatsis** [comment]
It seems like this feature is redundant (if you disagree, feel free to start a discussion and share your ideas on the Swift [forums](forums.swift.org)), but really I am closing this because the forums are a *much* better space for discussing quick ideas like these. I believe we want feature requests on GitHub to either provide more detail and motivation in the context of Swift or be opened after fruitful discussion on the forums to track progress on Swift Evolution proposals.
