### ISSUE TITLE
`collection literal could only be inferred to` diagnostic not shown in the presence of a contextual type

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#60011]
When a heterogeneous array literal could only be inferred to have type `[Any]`, the compiler humbly states that this may not match our expectation:

```swift
let array = [1, "Swift"] // error: heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional
```

However, this never seems to happen in the presence of a contextual type:

```swift
let array: any Sequence = [1, "Swift"] // OK?
```

**Expected behavior**
The compiler should not assume that a contextual type other than `[Any]` or, perhaps, `[Any?]` makes the inferred element type any more intentional. In this case, the error should be downgraded to a warning for source compatibility.

**Environment**
Swift version 5.8-dev (LLVM 116acf4edcf4f06, Swift d565ba5084a169d)

**Comment by danielfalbo** [comment]
If I'm understanding correctly, [`Sequence`](https://github.com/apple/swift/blob/dd3c90af3900339bf90a7ab6511612ba94e6d53a/stdlib/public/core/Sequence.swift#L325) has its `Element` associated type and [we can't](https://www.hackingwithswift.com/example-code/language/how-to-fix-the-error-protocol-can-only-be-used-as-a-generic-constraint-because-it-has-self-or-associated-type-requirements) have variables typed `any <Protocol>` if the `Protocol` has associated types. Therefore, we can't have a variable typed `any Sequence` regardless.

<img width="1076" alt="Screenshot 2022-07-28 at 11 17 15" src="https://user-images.githubusercontent.com/39460524/181469903-5caae96a-f308-42a8-a7a9-b53880c18cf7.png">

 Or is this another compiler bug and there's a hole in my understanding?

**Comment by AnthonyLatsis** [comment]
> If I'm understanding correctly, [`Sequence`](https://github.com/apple/swift/blob/dd3c90af3900339bf90a7ab6511612ba94e6d53a/stdlib/public/core/Sequence.swift#L325) has its `Element` associated type and [we can't](https://www.hackingwithswift.com/example-code/language/how-to-fix-the-error-protocol-can-only-be-used-as-a-generic-constraint-because-it-has-self-or-associated-type-requirements) have variables typed `any <Protocol>` if the `Protocol` has associated types.

Perhaps you are testing against a 5.6 compiler—[SE-0309](https://github.com/apple/swift-evolution/blob/main/proposals/0309-unlock-existential-types-for-all-protocols.md) is a 5.7 feature. You should still be able to reproduce the issue with older compilers using your own protocol and the old syntax:

```swift
protocol P {}
extension Array: P {}

let array: P = [1, "Swift"]
```

**Comment by simanerush** [comment]
@AnthonyLatsis I will work on this🤓

**Comment by AnthonyLatsis** [comment]
For the record, this was a premature idea. See #63982.
