### ISSUE TITLE
No warning or error is thrown when an instance of a class with mutable state instance is assigned to Sendable variable

### ISSUE THREAD

**Issue by muthuveerappanal** [apple/swift#60054]
**Describe the bug**
On Swift 5.7 (see environment) when an instance of a class with a mutable state is assigned to a `Sendable` variable, no warning error or error is thrown

```swift
class Engine {}

class Car {
    var engine: Engine
    init(engine: Engine) {
        self.engine = engine
    }
}

var car = Car(engine: Engine())
let s: Sendable = car
```

**Steps To Reproduce**
1. Using the environment mentioned below, create an Xcode command line project with the code mentioned above
2. Compile the code

**Expected behavior**
An error or warning needs to be thrown compiling the line `let s: Sendable = car`

**Environment**
 - OS: 13.0 Beta (22A5295i)
 - Xcode Version 14.0 beta 3 (14A5270f)
 - Xcode command line project

**Comment by hborla** [comment]
This is diagnosed under `-strict-concurrency=complete` in Swift 5.10

```
warning: type 'Car' does not conform to the 'Sendable' protocol
let s: Sendable = car
                  ^
note: class 'Car' does not conform to the 'Sendable' protocol
class Car {
      ^
```

**Comment by ollieatkinson** [comment]
@hborla this is still an issue today when using `targeted` mode - it's possible for mutable class types to gain implicit `Sendable` conformance.

Is there a way to stop implicit conformance to Sendable? It would be nice to enable the rule used in `complete` to stop this unsafe behaviour from compiling.

**Comment by hborla** [comment]
What it means for a context to require strict concurrency checking in targeted mode is defined [here](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0337-support-incremental-migration-to-concurrency-checking.md#concurrency-checking-modes)

> It is a closure with an explicit global actor attribute.
> 
> It is a closure or autoclosure whose type is async or `@Sendable`. (Note that the fact that the parent scope is in Minimal mode may affect whether the closure's type is inferred to be `@Sendable`.)
> 
> It is a declaration with an explicit nonisolated or global actor attribute.
> 
> It is a function, method, initializer, accessor, variable, or subscript which is marked async or `@Sendable`.
> 
> It is an actor declaration.

This does not include generic requirements to `Sendable` (including in existential types), which I think would be very difficult to determine because these conformance requirements can be implied by other declarations. In general, I don't think this approach of diagnosing violations in some contexts but not others is a good road to keep going down. It'd be better to introduce more granular upcoming features for certain categories of diagnostics that you can enable piecemeal.

**Comment by ollieatkinson** [comment]
I'm still not sure why implicit `Sendable` conformance is being given to `Car` when it's a mutable reference type, is this considered a bug? 

I appreciate wanting to move to strict concurrency checking, it's something I am working towards - but having this behaviour of implicit conformance without checking is leading to scenarios where a real NonSendable type (in my case, a thread confined db object) is being treated as Sendable.

**Comment by ollieatkinson** [comment]
Note, explicitly providing `Sendable` conformance correctly highlights this as a warning:

```
struct MaybeSendable: Sendable {
    let car: Car // Stored property 'car' of 'Sendable'-conforming struct 'MaybeSendable' has non-sendable type 'Car'; this is an error in the Swift 6 language mode
}
```
