### ISSUE TITLE
Nil coalescing operator leads to EXC_BAD_ACCESS in String(format:) method

### ISSUE THREAD

**Issue by Jacksoor** [apple/swift#60704]
**Describe the bug**
Using the nil coalescing operator avoids compiler type errors when used in the `String(format:)` method.

**Steps To Reproduce**
1. Create Playground with the following code
```swift
let x: Int? = 42
String(format: "%@", x ?? "")
```
2. Run playground
3. Playground is terminated with EXC_BAD_ACCESS

**Expected behavior**
Playground should not compile because `Int?` does not conform to `CVarArg`.

**Environment (please fill out the following information)**
 - OS: macOS 12.5.1
 - Xcode Version/Tag/Branch: 13.4.1 (13F100)

**Comment by LucianoPAlmeida** [comment]
I'm not sure this is a bug actually... what happens is that the contextual type is a `CVarArg` and given the overload available for `??` operator is `public func ?? <T>(optional: T?, defaultValue: @autoclosure () throws -> T)` application of the generic function ends up being bound to `(CVarArg?, @autoclosure () throws -> CVarArg) throws -> CVarArg` and given `Int` and `String` both conforms to `CVarArg` this type checks correctly because arguments satisfy the conformance and the result is an existential `CVarArg` where the wrapped concrete value can be either an `Int` or `String` (in case `x` is `nil`). 
This would be the same as: `let result: CVarArg = x ?? ""` where this type checks correctly because of the same reason.

> Playground should not compile because Int? does not conform to CVarArg.

But is not `Int?` that has to conform with `CVarArg` given the first argument is `T?` matching is `Int?` to `CVarArg?` after optional-to-optional restriction applied, the actual matching is `Int` conforms to `CVarArg` which is true.

And last, but not least the runtime crash is due to when unwrapping the existential value and seeing that is an `Int` in doesn't match with `%@` so that is expected behavior. So ...
```swift
let x: Int? = 42
String(format: "%d", x ?? "")
```
Works just fine although will crash at runtime if `x` is `nil` because `String` would not apply to `%d`.

So with that said I don't think this is a bug. But I'll let @xedin take a look as well to make sure I'm not missing anything :)

**Comment by Jacksoor** [comment]
Ah yes, it's correct that `Int` does not work in formatting with `%@`, I really thought I used that somewhere 😅 

My main confusion was also with the fact that, when just using x
```swift
let x: Int? = 42
String(format: "%d", x)
```
it would not compile because `Int?` does not conform with `CVarArg`. However, with a deeper insight into how the solver works here in conjunction with the `??` operator, it somehow makes sense that this is valid. I think this can be closed then.

**Comment by LucianoPAlmeida** [comment]
Yeah, it is a bit unexpected to see `??` on an `Int` producing a default `String` typecheck correctly which could lead to a confusion as well.

>  I think this can be closed then.

 I think it makes sense. Thanks!
