### ISSUE TITLE
Protocol types with class adoption limitation in generics

### ISSUE THREAD

**Issue by francuim-d** [apple/swift#61296]
Seems like in Swift 5.7 protocol types with class adoption limitation no longer acts like actual class type in generics

```swift
protocol Colorable: UIView { }

extension UIView {
    func subviews<T: UIView>(ofType type: T.Type) -> [T] {
        subviews.compactMap { $0 as? T }
    }
}

let view = UIView()
let colorableViews = view. subviews(ofType: Colorable.self)
```

**Actial behavior**
The code does not compiles with error: Instance method 'subviews(ofType:)' requires that 'any Colorable' inherit from 'AnyObject'

**Expected behavior**
The code compiles and correctly finds the subviews of the specified type.

**Environment**
 - macOS 12.6
 - Xcode 14.0.1 (14A400)

**Additional context**
That exact code compiles and works fine with Xcode 13.3.1

**Comment by theblixguy** [comment]
You just need to change the type of the argument from `T.Type` to `Any.Type`. Also, since the argument is not actually used, you can drop the `type` label and just do `ofType _: Any.Type`. That should allow your code to compile as expected.

**Comment by francuim-d** [comment]
> You just need to change the type of the argument from `T.Type` to `Any.Type`. Also, since the argument is not actually used, you can drop the `type` label and just do `ofType _: Any.Type`.
> 
> With this small change, your code should compile as expected.

If I replace T.Type with Any.Type then I will lose the ability to specify a concrete type using the function parameter. 
The method of specifying a concrete type with a function parameter is used here because this function is sometimes called in a context in which it cannot infer T by the return type.

And again, what confuses me is that with swift 5.6 the code is compiled and works exactly as it should.

**Comment by francuim-d** [comment]
In this thread on the Swift forum, the author faced the same problem.
https://forums.swift.org/t/weird-error-from-the-compiler-when-using-xcode-14/60119

**Comment by theblixguy** [comment]
> If I replace T.Type with Any.Type then I will lose the ability to specify a concrete type using the function parameter.

Sorry, I don't understand. The example below works fine for me:

```swift
import UIKit

protocol Colorable: UIView { }

extension UIView {
    func subviews<T: UIView>(ofType _: Any.Type) -> [T] {
        subviews.compactMap { $0 as? T }
    }
}

final class MyColorableView: UIView, Colorable {}

let view = UIView()
view.addSubview(MyColorableView())

print(view.subviews(ofType: Colorable.self)) // ok
print(view.subviews(ofType: MyColorableView.self)) // ok
```

**Comment by theblixguy** [comment]
Ah ok, I see the problem. So you have a `T: UIView` constraint, which means it needs a concrete type that inherits from `UIView`. But you're passing it `any Colorable`, which is an [existential](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md) and does not inherit from `UIView`.

**Comment by theblixguy** [comment]
Ok, sorry I misunderstood your problem here. So I think what the problem here is that your function has a `T: UIView` constraint (which also implies `T: AnyObject)` but you're passing `any Colorable`, which is an existential box and so does not satisfy that constraint. It's the type that conforms to `Colorable` that satisfies the constraint, so for example if you pass `MyColorableView` then that's ok. 

If you want to learn more about `any` types, you can look at https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md

**Comment by theblixguy** [comment]
Ah okay, I should've looked at it more closely, sorry.

**Comment by theblixguy** [comment]
So I think this error is happening because you have a `T: UIView` constraint on the function, which `any Colorable` (which is an [existential box](https://github.com/apple/swift-evolution/blob/main/proposals/0335-existential-any.md)) does not satisfy as it does not inherit from `UIView` (it's the type that it contains that inherits from it).

We do have an [implicit](https://github.com/apple/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md) mechanism to "open" the existential box, but I don't think it applies here.

**Comment by francuim-d** [comment]
Thanks for your reply. I studied the proposals. I understood the concept of existential types, but I wonder why this code works in swift 5.6, which already contains existential types. And is it possible to somehow write the same code that would work in swift 5.7+

**Comment by AnthonyLatsis** [comment]
This was a type safety hole. You should not be able to bind `T` to `P` by passing a *protocol metatype* instance `P.self` of type `P.Protocol` to this function, because a protocol metatype is not associated with any concrete type `T` that conforms to the protocol. For example, the 5.5.2 compiler lets the following code through, resulting in a run-time crash.

```swift
class C {
  class func test() {
    print("Hello, World!")
  }
}
protocol P: C {}

func f1<T: C>(_: T.Type) {
  T.test()
}

f1(P.self)
```

What you can pass is an *existential metatype* instance of type `P.Type`, a runtime box that encapsulates a metatype value of a concrete type that actually conforms to the protocol:

```swift
func f2(_ p: P.Type) {
  // Under the hood, 'p' is upcasted to 'C.Type' before being passed to 'f1'. 
  f1(p)
}

class Sub: C, P {}
f2(Sub.self) // Hello, World!
```
> **Note**
> What really happens here is that `p` gets implicitly upcasted to `C.Type` before being passed to `f1`.

___

This is also why you cannot do `let _: P.Protocol = Sub.self`, unlike `let _: P.Type = Sub.self`.
