### ISSUE TITLE
UnsafeMutableBuffer bad access when subscript concurrently

### ISSUE THREAD

**Issue by Vaida12345** [apple/swift#61903]
**Describe the bug**
```swift
public extension Array {

    /// Initialize the array concurrently.
    ///
    /// - Warning: use the concurrent implications only when the complexity of `work` is high.
    ///
    /// **Example**
    ///
    /// ```swift
    /// Array<T>(iterations: self.count) { index in
    ///     transform(self[index])
    /// }
    /// ```
    ///
    /// - Parameters:
    ///   - iterations: The number of elements in the array.
    ///   - execute: The closure which generates the element at the `index`.
    init(iterations: Int, execute work: (_ index: Int) -> Element) {
        self.init(unsafeUninitializedCapacity: iterations) { buffer, initializedCount in
            DispatchQueue.concurrentPerform(iterations: iterations) { index in
                let result = work(index)
                buffer[index] = result // bad access here
            }
            initializedCount = iterations
        }
    }
}
```
This code snippet would result in bad access under certain situations when `Element` is `CGImage`.

**Steps To Reproduce**
```swift
[CGImage](iterations: 100) { doSomethingReturnsCGImage($0) }
```
This error was observed in my large project, which is difficult to be shown here.

**Workaround**
```swift
public extension Array {

    init(iterations: Int, execute work: (_ index: Int) -> Element) {
        self.init(unsafeUninitializedCapacity: iterations) { buffer, initializedCount in
            let start = buffer.baseAddress!
            
            DispatchQueue.concurrentPerform(iterations: iterations) { index in
                 let result = work(index)
                 (start + index).initialize(to: result)
            }
            initializedCount = iterations
        }
    }
}
```

**Comment by karwa** [comment]
This is expected behaviour, but it has nothing to do with concurrency. The subscript performs an _assign_ operation, which expects that the memory location is already initialized to a value, and will deinitialize the existing contents before reinitializing it with the new value.

Since, in your example, the memory location has _not_ previously been initialized to a value, deinitializing it invokes undefined behaviour, and the workaround, as you have discovered, is to instead use an initializing operation, rather than assignment operation, for that location.

This is documented in [`UnsafeMutablePointer.subscript`](https://developer.apple.com/documentation/swift/unsafemutablepointer/subscript(_:)). Perhaps we should add this note to UnsafeMutable_Buffer_Pointer's subscript, too:

> When the subscript is used as the left side of an assignment, the memory at `p + i` must be initialized or the pointer’s Pointee type must be a trivial type.
>
> Do not assign an instance of a nontrivial type through the subscript to uninitialized memory. Instead, use an initializing method, such as `initialize(repeating:count:)`.

By the way, the documentation for `UMBP.subscript` is _suuuuuper well-hidden_. It's actually tucked away in the "MutableCollection implementations" section of the UMBP docs. In the unlikely event that anybody happened to [find it](https://developer.apple.com/documentation/swift/unsafemutablebufferpointer/subscript(_:)-9t9gq), it still doesn't contain this warning. But it should.

**Comment by Vaida12345** [comment]
I see, thank you! I think it's better to add a line of documentation for the `UnsafeMutableBufferPointer.allocate(capacity:)`, stating that uninitialized memory should be initialized with `initialize(to)`, not `subscript`.

**Comment by AnthonyLatsis** [comment]
You are welcome to open a new issue requesting an improvement to the documentation.
