### ISSUE TITLE
Instance of Type with primary associated type is not Type<Any>

### ISSUE THREAD

**Issue by Vaida12345** [apple/swift#61998]
**Describe the bug**
```swift

struct Foo<T> {
    
    let value: T
    
}

let instance = Foo(value: 123)
print(instance is Foo<Any>) // false

let arrayInstance = [1, 2, 3]
print(arrayInstance is Array<Any>) // true
```
As it can be shown above, the `instance` of `Foo<Int>` `is` not `Foo<Any>`, with the compiler stating that "Cast from 'Foo<Int>' to unrelated type 'Foo<Any>' always fails". However, instance of `Array<Int>` `is` `Array<Any>`

**Expected behavior**
`instance is Foo<Any>`->`true`.

**Environment (please fill out the following information)**
 - OS: macOS 13.0
 - Xcode Version/Tag/Branch: 14.1 (14B47b)

**Additional context**
If this is the expected behavior, could you please give a hint on how SwiftUI managed to know the type of View its associated type?

**Comment by AnthonyLatsis** [comment]
This is expected behavior. Generic types are invariant in Swift, meaning that `Int` being a subtype of `Any` does not imply that `Foo<Int>` is a subtype of `Foo<Any>`. `Array`, `Set` and `Dictionary` are exceptions backed by the compiler.

> If this is the expected behavior, could you please give a hint on how SwiftUI managed to know the type of View its associated type?

Could you clarify how you think this is related to SwiftUI and the `View` protocol?
