### ISSUE TITLE
Bootstrapping broken for Ninja builds on Apple silicon Macs (arm64)

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#62017]
**Steps To Reproduce**
Build via Ninja on an Apple silicon Mac and [spot check your build](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#spot-checking-an-incremental-build). Unlike `bootstrapping0/bin/swift-frontend`, `bin/swift-frontend` does not get rebuilt and hence does not reflect the change.

**Comment by eeckstein** [comment]
The problem is that, due to reasons which go beyond my cmake knowledge, `ninja swift-frontend` doesn't necessarily refer to the `bin/swift-frontend` executable, but to a bootstrapping swift-frontend.
Using `ninja bin/swift-frontend` solves the problem. I updated the docs: https://github.com/apple/swift/pull/63381

**Comment by AnthonyLatsis** [comment]
@eeckstein Thanks a lot! I didn’t know you could pass a path to an executable, a not a registered target name, to `ninja`. Is this common practice internally?

**Comment by eeckstein** [comment]
> Is this common practice internally?

I think it depends what you want to do.
