### ISSUE TITLE
Heterogeneous integer comparisons produce suboptimal code

### ISSUE THREAD

**Issue by karwa** [apple/swift#62260]
**Description**

Consider two Swift functions, both comparing an `Int` with a `UInt32`:

```swift
func compare_direct(_ x: Int, _ y: UInt32) -> Bool {
    x < y
}

func compare_widened(_ x: Int, _ y: UInt32) -> Bool {
    x < Int(y)
}
``` 

These compile to vastly different code.

The versions which widens `y` compiles to a simple `cmp` instruction:

```asm
output.compare_widened(Swift.Int, Swift.UInt32) -> Swift.Bool:
        mov     eax, esi
        cmp     rax, rdi
        setg    al
        ret
```

But the version which performs the comparison directly compiles to a whole algorithm:

```asm
output.compare_direct(Swift.Int, Swift.UInt32) -> Swift.Bool:
        test    rdi, rdi
        js      .LBB1_1
        jne     .LBB1_6
        test    esi, esi
        jne     .LBB1_6
        xor     eax, eax
        ret
.LBB1_1:
        mov     al, 1
        ret
.LBB1_6:
        mov     eax, esi
        cmp     rax, rdi
        seta    al
        ret
```

**Steps to reproduce**

[Godbolt](https://swift.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:swift,selection:(endColumn:2,endLineNumber:7,positionColumn:2,positionLineNumber:7,selectionStartColumn:2,selectionStartLineNumber:7,startColumn:2,startLineNumber:7),source:'func+compare_direct(_+x:+Int,+_+y:+UInt32)+-%3E+Bool+%7B%0A++++x+%3C+y%0A%7D%0A%0Afunc+compare_widened(_+x:+Int,+_+y:+UInt32)+-%3E+Bool+%7B%0A++++x+%3C+Int(y)%0A%7D'),l:'5',n:'0',o:'Swift+source+%231',t:'0')),k:54.577893820713676,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:swiftnightly,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:swift,libs:!(),options:'-O',selection:(endColumn:12,endLineNumber:20,positionColumn:1,positionLineNumber:5,selectionStartColumn:12,selectionStartLineNumber:20,startColumn:1,startLineNumber:5),source:1),l:'5',n:'0',o:'+x86-64+swiftc+nightly+(Editor+%231)',t:'0')),k:45.42210617928634,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Expected behavior**

These functions do the same job (I think -- always a dangerous assumption to make with numerics 😅); they should compile to the same code. The single-`cmp` variant would appear to be the optimal solution.

**Environment**

- Swift compiler version info

```
Swift version 5.7 (swift-5.7-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by LucianoPAlmeida** [comment]
That is because overload resolution selects different operators for them, while compare `compare_widened` is resolved to `decl=Swift.(file).Int.<` which is a simple `Builtin.cmp` https://github.com/apple/swift/blob/1f3e159cfe518fbb723230a4e8f562248d34d863/stdlib/public/core/IntegerTypes.swift.gyb#L1234 and `Int(y)` is optimized away.
But for direct one, compiler has no choice but to choose `decl=Swift.(file).BinaryInteger extension.< [with (substitution_map generic_signature=<Self, Other where Self : BinaryInteger, Other : BinaryInteger> (substitution Self -> Int) (substitution Other -> UInt32))]` which is a bit more code that has additional safety checks is not as straight forward to optimize.
https://github.com/apple/swift/blob/1f3e159cfe518fbb723230a4e8f562248d34d863/stdlib/public/core/Integers.swift#L1732 

Note, I agree that this is indeed something that could be generating better code, maybe is stdlib defining specialized overloads? Maybe improvements on optimizer(But that is just guessing, I'm definitely have a very limited knowledge on that area)?

**Comment by AnthonyLatsis** [comment]
cc @stephentyrone

**Comment by AnthonyLatsis** [comment]
I think this issue should be addressed to the Standard Library implementation. Couldn’t the generic heterogeneous comparison algorithm simply do a homogeneous comparison, widening the left- or right-hand side depending on their `bitWidth`s? 
```swift
extension BinaryInteger {
  @_transparent
  public static func < <Other: BinaryInteger>(lhs: Self, rhs: Other) -> Bool {
    if lhs.bitWidth > rhs.bitWidth {
      return lhs < Self(rhs)
    } else {
      return Other(lhs) < rhs
    }
  }
}
```

A specialization of this for fixed-width integers results in the supposedly desired codegen. Though, maybe the current algorithm was balanced or designed to be optimal for both fixed- and non-fixed-width integers, whatever that is.

**Comment by LucianoPAlmeida** [comment]
> Couldn’t the generic heterogeneous comparison algorithm simply do a homogeneous comparison, widening the left- or right-hand side depending on their `bitWidth`s?

My question would be if that would be semantically correct for signed/unsigened compare operations? Like if we have a `Int` > `UInt64` in a 64-bit platform. Because for what I see from current implementation that is the early extra check it has to perform and IIUC that is the extra code we see in the final assembly.

**Comment by AnthonyLatsis** [comment]
Ah, right, then we can widen the unsigned operand if the bit widths are equal. The `isSigned` checks are optimized away after specialization, it’s the `== 0` checks and branches that contribute to the jumps and `test` instructions.
