### ISSUE TITLE
iOS 16 onOpenUrl delegate not implemented

### ISSUE THREAD

**Issue by tanghengliang** [apple/swift#62433]
The onOpenUrl method receives the enterprise WeChat login callback delegation method, which is not implemented. For example, the onResp method is not implemented, and the code cannot be obtained

**Comment by AnthonyLatsis** [comment]
This does not sound like a compiler issue. If this is an issue with the implementation of a proprietary Apple framework (I am assuming SwiftUI), please report it at https://feedbackassistant.apple.com. If you still believe the problem lies with the implementation of the compiler, please provide a test case and explain the problem based on it.
