### ISSUE TITLE
CodingKeyRepresentable is incorrectly available under low deployment targets

### ISSUE THREAD

**Issue by endeavour42** [apple/swift#62769]
**Description**
A type adopting `CodingKeyRepresentable` should not compile when deployment target is set to less than:
macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4

**Steps to reproduce**
- compile the sample app below, it's single file SwiftUI app
- set deployment target to a lower value. For test I'm using iOS 14.0. macOS 12.0 should also show the issue.
- try to compile the app - it compiles OK but it should not
- when you run the app on a device that doesn't support `CodingKeyRepresentable` (e.g. iOS 15.2 or macOS 12) the app doesn't work correctly.

**Expected behavior**
There should be a compilation error when deployment target is set to low value. Perhaps a corresponding fix-it should suggest either setting deployment target to higher value or offering a conditional "#if" branch.

**Environment**
- Swift compiler version info version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
- Xcode version info Xcode 14.0.1 Build version 14A400
- Deployment target: iOS 14.0

**Sample app**
```Swift
// set --minimum-deployment-target 14.0
//
// The following app should not compile with low deployment targets as:
// @available(macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4, *)
// public protocol CodingKeyRepresentable {

import SwiftUI

var initCalled = false
var keyCalled = false

struct SmartKey: Hashable, Codable, CodingKey, CodingKeyRepresentable {
    let string: String

    var stringValue: String {
        string
    }
    init?(stringValue: String) {
        self.string = stringValue
    }
    var intValue: Int? {
        nil
    }
    init?(intValue: Int) { fatalError() }
    
    init?<T>(codingKey: T) where T : CodingKey {
        initCalled = true
        string = codingKey.stringValue
    }
    
    var codingKey: CodingKey {
        keyCalled = true
        return self
    }
}

struct S: Codable, Equatable {
    var dict: [SmartKey : String]
}

func test() {
    print("start")
    let v = S(dict: [SmartKey(stringValue: "name")! : "value"])
    let data = try! JSONEncoder().encode(v)
    precondition(keyCalled)
    let string = String(data: data, encoding: .ascii)!
    precondition(string == #"{"dict":{"name":"value"}}"#)
    let v2 = try! JSONDecoder().decode(S.self, from: data)
    precondition(initCalled)
    precondition(v == v2)
    print("done")
}

struct ContentView: View {
    var body: some View {
        Text("Hello, World!")
    }
}

@main struct CKRTApp: App {
    init() {
        test()
    }
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**Comment by tshortli** [comment]
This behaves as expected; there is no type checking rule violated by conforming a more available type to a less available protocol. Ideally there would be an availability-gated entry point to using the requirements of the protocol, but since that is opaquely hidden behind `JSONEncoder.encode` and `JSONDecoder.decode` methods there's nothing the compiler can statically type check here.

**Comment by jesus-mg-ios** [comment]
@tshortli @AnthonyLatsis It behaves as expected from the compiler’s perspective, but not in the way we expected. Could this be considered an improvement rather than a bug?

Does the following suggestion make sense?

===============
Proposal: 

**Issue:**
Currently, the Swift compiler doesn’t flag potential availability mismatches between a protocol and a conforming type, even when the protocol is marked as available only on specific OS versions. When a type that’s available across a broader range of OS versions (like iOS 14+) conforms to a protocol that is only available on a narrower set of versions (like iOS 15+), the compiler allows this without ensuring that the availability matches, which can lead to runtime issues.

**Improvement:**
If the symbol of the protocol is included in the final compiled binary, the compiler should have a way to detect this and verify that the protocol's availability constraints are respected. Specifically:

**Symbol availability detection**: Once the protocol symbol is part of the binary, the compiler should be able to detect this and check that the conformance to the protocol aligns with the protocol’s availability.
If the type's availability and the protocol’s availability don’t match, the compiler should raise a warning or error, flagging that the symbol is available in the binary but doesn’t align with the required availability levels.

**Comment by jesus-mg-ios** [comment]
@shahmishal
