### ISSUE TITLE
[Source compatibility suite] swift compiler hanging when attempting to build swift-nio file Utilities.swift

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#62837]
**Describe the bug**
Multiple projects within the source compatibility suite are failing to build and timing out during their build process. All projects in question appear to be hanging when attempting to compile [`NIOPosix/Utilities.swift`](https://github.com/apple/swift-nio/blob/main/Sources/NIOPosix/Utilities.swift)

From the build logs you can see 
```
swift-frontend -frontend -c <ARGS> /swift-source-compat-suite/project_cache/swift-nio-extras/.build/checkouts/swift-nio/Sources/NIOPosix/Utilities.swift <ARGS> -o /swift-main-source-compat-suite/swift-source-compat-suite/project_cache/swift-nio-extras/.build/x86_64-apple-macosx/release/NIOPosix.build/Utilities.swift.o
sandbox-exec: Timed out
```

I've omitted certain args to make the report more readable but you can find the entire command here:
https://ci.swift.org/job/swift-main-source-compat-suite/286/artifact/swift-source-compat-suite/FAIL_swift-nio-http2_5.0_BuildSwiftPackage.log

Source compatibility projects which are affected:
* async-http-client
* grpc-swift
* Moya
* mqtt-nio
* swift-nio-extras
* swift-nio-http2
* swift-nio-ssh
* swift-nio-ssl
* swift-nio-transport-services

Note that these timeouts only occur when building the projects for 5.0 in release config (not debug)

This issue first occurred during the nightly run on Dec 22nd. When comparing https://www.swift.org/download/ nightly snapshots from 
* Dec 21st -> The issue does not occur
* Dec 29th -> The compiler hangs and causes the timeouts.

**Expected behavior**
Expecting the projects to build correctly

**Environment**
```
Apple Swift version 5.8-dev (LLVM ab856b0fa3177ee, Swift 71c62c04ace2b5b)
```

https://ci.swift.org/job/swift-main-source-compat-suite/286

To reproduce, do the following.
1.) Download the Dec 29th toolchain from the swift.org download link above
2.) Clone https://github.com/apple/swift-nio-extras and checkout [`55f37f3`](https://github.com/apple/swift-nio-extras/commit/55f37f3)
3.) Run 
```
<PATH-TO-swift-DEVELOPMENT-SNAPSHOT-2022-12-29-a.xctoolchain>/usr/bin/swift build --disable-sandbox --package-path <PATH_TO_SWIFT_NIO_EXTRAS> --verbose --configuration release --build-tests -Xswiftc -swift-version -Xswiftc 5 -Xswiftc -disallow-use-new-driver -Xswiftc -enable-testing
```
And observe that the compiler will hang when attempting to compile Utilities.swift

**Comment by justice-adams-apple** [comment]
For now, I will xfail the associated projects

**Comment by shahmishal** [comment]
`git log --oneline --no-merges swift-DEVELOPMENT-SNAPSHOT-2022-12-21-a..swift-DEVELOPMENT-SNAPSHOT-2022-12-29-a ` 
b0e5502e1e4 lib: fix typo in Type.cpp
ef12ec7b2c4 COWOpts: fix a crash in case a buffer "escapes" to a cond_br condition
da51c04116b Two of the macros tests are failing to import SwiftDiagnostics.
62bf6d55ecb [Test] Disable async_task_cancellation_taskGroup on backdeployed runtimes
75aace0f409 Remove the old EscapeAnalysis
c130273859d Remove the old SideEffectAnalysis
afedd6d72f6 copy required stuff from SideEffectAnalysis to AccessStorageAnalysis
beb46eb624d Use the new escape and side effects in alias analysis
814d8909466 Use the new side effects in LICM
f0825842304 Use the new side effects in CSE
2d67ab2b56e [cxx-interop] Import non-member operators as global functions
508708919ae ClosureLifetimeFixup: Fix corner case of unconnected basic blocks
e966b4ef7d9 [CSDiagnostics] Add an error message for pack expansion expressions over packs that don't have the same shape.
8956de43a32 [ConstraintSystem] Audit remaining arguments for packElementOpener to type resolution.
21b4004d69d Devirtualizer: don't de-virtualize witness calls to non-generic thunks which call a generic function.
58953567b3d [CSGen] Use PackExpansionExpr::getExpandedPacks to generate ShapeOf constraints rather than relying on PackElementExprs collected by preCheck.
b977adfbdb1 [AST] Add a helper method to PackExpansionExpr that gathers all packs that are expanded within the pattern.
2df72f6bccf [ConstraintSystem] Strip pack expansions off of pack reference types in getUnopenedTypeOfReference.
a2346db4456 [ConstraintSystem] Add a getAsTypeRepr helper method for casting ASTNodes.
1ba0462c270 [Task-to-Thread] Make sure to explicitly initialize the drainLock in DefaultActorImpl::initialize or we could end up waiting on a garbage lock value
18fd8457327 Create begin_borrow in OSSA only
b8ce8997e5a [Test] Add tests for pack element reprs outside pack expansion expressions.
334efb9975f [ConstraintSystem] Always pass in a direct instance of OpenPackElementType instead of assigning it to std::function_ref.
7a593ce1eaa [Sema] Teach `LocalDiscriminatorsRequest` about runtime attribute initializers
932c6eb64d9 [Tests] RuntimeMetadata: Add test-cases for attributes on methods of inner types
4a918324ce2 [Sema] RuntimeMetadata: Allow declaring `init(attachedTo:)` overloads in extensions
02937a7165c [Sema] RuntimeMetadata: Supress attr inference for local types
74fdd58ad18 [SILGen] RuntimeMetadata: Change attribute generator to always produce result indirectly
8af9b14428b Only touch the MetadataSections::swift5_runtime_attributes field in newer structures
43904e5a894 [ASTPrinter] Mark declarations with runtime attributes as using the feature
11033c6aa46 Fill out dynamic loading of the runtime attributes section
a5af302173a [stdlib] RuntimeMetadata: Register newly added "runtime attributes" section
a98a35e2b3c [Sema] RuntimeMetadata: Verify that runtime attribute has a valid initializer
5a1f197d9bc [Sema] RuntimeMetadata: Workaround for availability checking of generator expressions
618b9d943af [Sema] RuntimeMetadata: Use `CustomAttrTypeRequest` while synthesizing generator expression
f7f2e3709b1 [Sema] RuntimeMetadata: Synthesize a body for runtime attribute generator
76f352db3db [Sema/IRGen] NFC: add IRGen test for runtime discoverable attributes
b83b0943b52 [SILDeclRef] RuntimeMetadata: Add a special kind for runtime attribute generator
91042d77aa5 [SILGen] Make it possible to emit generator function given its body and result type
bcaaa91a53c [IRGen] Linking: Get AccessibleFunction parent module directly
8a930095fe2 [AST/Sema] RuntimeMetadata: Switch generator synthesis to produce an expression
7d54af84ea1 [AST] RuntimeMetadata: Add new initializer context to cover runtime attrs
6c1f37afdac [AST] Add mangling for runtime attribute generators
8de03a2b38d [ABI] Metadata: Add a runtime discoverable attribute and its entry
5442d30866c [IRGen] RuntimeMetadata: Emit runtime discoverable attributes section
8a74986964c [Sema] RuntimeMetadata: Add type decl accessor for runtime metadata attribute
59d6509d558 [IRGen] Make it possible to get address of accessible func record
b8819373d9d [IRGen] RuntimeMetadata: Add linking record for runtime discoverable attrs
52cec67a6ad [ABI/Mangling] RuntimeMetadata: Add mangling for runtime discoverable attr records
0c5e133ab49 [IRGen] Add runtime accessible functions to a special section
f7ee0728109 [Serialization] SILFunction: handling for "runtime accessible" attribute
3fb69b3c3c4 [SIL] SILFunction: Add `runtime accessible` function attribute
5afccec9172 [AST] RuntimeMetadata: Register all decls with runtime discoverable attrs that appear in a file
4806e74fad2 [AST/Decl] RuntimeMetadata: Make it possible to retrieve a generator for a given attr
84c2ff64457 [SILDeclRef] Make it possible to identify references to runtime accessible entities
8e66f193c12 [AST/Sema] RuntimeMetadata: Add a way to retrieve runtime metadata attrs
91f995c1e07 [TypeChecker] RuntimeAttr: Add skeleton generator implementation
01fb1f82989 [Sema] RuntimeMetadata: Implement custom attribute placement validation
8c5e1b66d27 [AST/Sema] RuntimeMetadata: make it possible to use unbound generic types as runtime metadata attributes
7b35e85d317 [PreCheckExpr] Consider postfix ellipsis expressions containing 'each' type reprs to be pack expansion expressions.
27aa3651e8c [ConstraintSystem] Open pack element types using a PackElementOf constraint when resolving pack reference type reprs inside pack expansion expressions.
454913aeb5c [TypeResolution] Plumb a pack element opener function through type resolution.
01b5a9d1822 [DI] TypeWrappers: Support conformance requirements on Wrapper/Storage parameters
4a0f9cac72d [SILGen] TypeWrappers: force emission of wrapper initializer
d1bb5add172 [SILGen] TypeWrappers: Handle initialization of property wrapped fields without init exprs
9b2b8b3a49c [stdlib] Correct actual print outputs in Concurrency files
1d3b70d66c8 build: Make `--xcode` imply `--skip-early-swiftsyntax`
e2febeadaf4 Demangle an OpaqueArchetypeTypeRef's ID as a type not as a symbol

**Comment by eeckstein** [comment]
Should be fixed by https://github.com/apple/swift/pull/62830

**Comment by eeckstein** [comment]
https://github.com/apple/swift/pull/62830 is merged and this should be resolved now.
