### ISSUE TITLE
Swift fails to select correct overloaded function with Decimal

### ISSUE THREAD

**Issue by jasonbobier** [apple/swift#63428]
The following code produces the error: `member 'attributed' in 'Decimal.FormatStyle' produces result of type 'Decimal.FormatStyle.Attributed', but context expects 'Decimal.FormatStyle`

```
public func formatted(_ formatStyle: Decimal.FormatStyle) -> String {
	Decimal(1).formatted(formatStyle)
}

public func formatted(_ formatStyle: Decimal.FormatStyle.Attributed) -> AttributedString {
	Decimal(1).formatted(formatStyle)
}

formatted(.number.attributed)
```

But this code works fine:

```
public func formatted(_ formatStyle: IntegerFormatStyle<Int>) -> String {
	1.formatted(formatStyle)
}

public func formatted(_ formatStyle: IntegerFormatStyle<Int>.Attributed) -> AttributedString {
	1.formatted(formatStyle)
}

formatted(IntegerFormatStyle<Int>.number.attributed)
```

**Environment**
- Swift compiler version info: swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

- Xcode version info: Version 14.2 (14C18)

**Comment by LucianoPAlmeida** [comment]
I think this is expected behavior, to make the first case to work we have to specify the base `formatted(Decimal.FormatStyle.number.attributed)` because basically when base is not specified `.number.attributed` when attempting each overload solver will try infere base from context which in for first overload that takes `Decimal.FormatStyle` base will be attempted as `**Decimal.FormatStyle**.number.attributed` which fails with mismatch because the result of it is `Decimal.FormatStyle.Attributed` but parameter expects `Decimal.FormatStyle`. And when attempting second overload that takes `Decimal.FormatStyle.Attributed` base will be inferred as `**Decimal.FormatStyle.Attributed**.number.attributed` which fails because that type has no member `number`. 
This results in no overload matching `formatted(.number.attributed)`
Note that second example works because you do specify base.

**Comment by jasonbobier** [comment]
Yep. That makes sense to me as well. And once Foundation is open sourced, I'll sneak in a .number for Decimal.FormatStyle.Attributed, so it all looks pleasant. :)

**Comment by LucianoPAlmeida** [comment]
We could get away with that by using extensions in your context
```swift
public func formatted(_ formatStyle: Decimal.FormatStyle) -> String {
  Decimal(1).formatted(formatStyle)
}

public func formatted(_ formatStyle: Decimal.FormatStyle.Attributed) -> AttributedString {
  Decimal(1).formatted(formatStyle)
}

extension Decimal.FormatStyle.Attributed {
  static var number: Decimal.FormatStyle.Attributed { Decimal.FormatStyle.number.attributed }
}

// Now inference can work with `Decimal.FormatStyle.Attributed` as base.
let _: AttributedString = formatted(.number) // Picks second overload
let _: String =  formatted(.number) // Picks first overload 
```

**Comment by jasonbobier** [comment]
That's almost what I did. I extended it like this:

```
public func formatted(_ formatStyle: Decimal.FormatStyle) -> String {
	Decimal(1).formatted(formatStyle)
}

public func formatted(_ formatStyle: Decimal.FormatStyle.Attributed) -> AttributedString {
	Decimal(1).formatted(formatStyle)
}

extension Decimal.FormatStyle.Attributed {
	static var number: Decimal.FormatStyle { Decimal.FormatStyle.number }
}

formatted(.number)
formatted(.number.attributed)
```

To keep `.number` and `.number.attributed` consistent in meaning with their current versions (.i.e. number is String based and number.attributed is AttributedString based).
