### ISSUE TITLE
The public @inlinable method using the @usableFromInline-marked internal property results in an error when BUILD_LIBRARY_FOR_DISTRIBUTION is set to YES.

### ISSUE THREAD

**Issue by CrazyFanFan** [apple/swift#66669]
**Description**

The public @inlinable method using the @usableFromInline-marked internal property results in an error when BUILD_LIBRARY_FOR_DISTRIBUTION is set to YES.

```swift
import Foundation

public struct FooStruct {
    @usableFromInline
    internal let foo: Int

    @inlinable
    public init(foo: Int) {
        self.foo = foo
    }
}
```
Error: `'let' property 'foo' may not be initialized directly; use "self.init(...)" or "self = ..." instead`

But using`@inline(__always)` makes it compile:

```swift
import Foundation

public struct FooStruct {
    @usableFromInline
    internal let foo: Int

    @inline(__always)
    public init(foo: Int) {
        self.foo = foo
    }
}
```

**Steps to reproduce**

1. Create a framework project using Xcode.
2. Create a Swift file and paste the erroneous code from above into it.
3. Open "Build Settings" and set 'BUILD_LIBRARY_FOR_DISTRIBUTION' to 'YES'.
4. build and wait for the error to occur

**Expected behavior**

 Build success and product a framework.

**Environment**
- Swift compiler version info 
> swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
> Target: arm64-apple-macosx13.0

- Xcode version info 
> Xcode 14.3.1
> Build version 14E300c

- Deployment target: 
> iOS 16.4

[Demo.zip](https://github.com/apple/swift/files/11757510/Foo.zip)

**Comment by grynspan** [comment]
This is happening because the public, inlinable initializer cannot directly reference the structure's underlying storage and must go through an accessor function (because that's what's available to callers.) You can bypass this problem by adding a non-inlinable `@usableFromInline internal` initializer that assigns to `self.foo` and having the public initializer call it.

Alternatively, if the layout of this structure will never change, you can mark it `@frozen`, at which point the existing code should compile.
