### ISSUE TITLE
Defining / as a Custom Operator Can Cause Parsing Errors

### ISSUE THREAD

**Issue by aetherealtech** [apple/swift#67517]
**Description**
Currently, `/` is a legal first character of a custom operator.  However, if such a custom operator is used in a line that also includes a string literal that contains a `/`, the parser will treat the characters between the two `/` characters as a regex literal.

This raises the question of whether this is a parsing bug, or if `/` should be banned as an operator symbol.

The problem can be avoided by splitting the expression onto multiple lines so that the `/` characters are on different lines.

**Steps to reproduce**
Try to compile the following code:

```swift
prefix operator /

extension Int {
    static prefix func /(value: Int) -> Int {
        return value
    }
}

func breakMe() {
    let working: (Int, Int, String) = (
        /5, /10,
         "Uh/Oh"
    )

    let broken: (Int, Int, String) = (/5, /10, "Uh/Oh")

}
```

The `broken` expression breaks the parser.   Any such expression that contains a use of the prefix operator followed by a string literal containing `/` sometimes (but strangely not always) causes compilation failures, and appears to always cause parse failures.  The code is highlighted in such a way that all the characters between the second and third `/` are red (string literal).

**Expected behavior**
Either the code on a single line is legal, and it should parse correctly, with the parser able to identify that the last `/` is not a control character but part of a string literal, or if it is impossible to distinguish this from a true regex literal, `/` should possibly be banned as an operator symbol.

![Screenshot 2023-07-25 at 3 03 37 PM](https://github.com/apple/swift/assets/97366903/30de5476-5a6d-4124-98fc-3dab0315bb0b)

**Environment**
- swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
- Xcode 14.3.1 Build version 14E300c
- iOS 15/16

**Comment by AnthonyLatsis** [comment]
let broken: (Int, Int) = (/5,/10)

**Comment by hamishknight** [comment]
This is behaving as expected, we will not parse a regex if it starts or ends with a space, so `/5, /10` is fine, but `/10, "Uh/Oh"` will indeed be parsed as a regex. You can disambiguate the use of a prefix operator containing `/` by using parens, e.g:

```swift
    let disambiguated: (Int, Int, String) = ((/5), (/10), "Uh/Oh")
```

See https://github.com/apple/swift-evolution/blob/main/proposals/0354-regex-literals.md#how--is-parsed for more info on the parsing rules.

> This raises the question of whether this is a parsing bug, or if `/` should be banned as an operator symbol.

We can't totally ban `/` as an operator symbol because the stdlib defines infix `/` and `/=`, though personally I'm not against us deprecating `/` as a prefix operator character. Though I don't think we'd want to consider that until we support case paths as a language feature, as https://github.com/pointfreeco/swift-case-paths is a fairly popular library currently relying on prefix `/`.
