### ISSUE TITLE
Is it possible to access generic member property of a protocol with an associatedtype?

### ISSUE THREAD

**Issue by heecheon92** [apple/swift#67612]
I have come across a problem where it makes me wonder is it possible to access a generic member property of a struct that conforms to a protocol with an associatedtype.

For example:

```swift
protocol P {
    associatedtype T
    var generic: G<T> { get }   // <- This guy is the problem.
    var value: T { get }
}

struct G<T> { var wrappedValue: T }

struct S1: P {
    typealias T = Int
    var generic = G(wrappedValue: 1)
    var value = 1
}

struct S2: P {
    typealias T = String
    var generic = G(wrappedValue: "hi")
    var value = "hi"
}

struct S3: P {
    typealias T = Double
    var generic = G(wrappedValue: 1.9)
    var value = 1.9
}
```

I have a protocol P with an associatedtype T and has a protocol requirement of a generic member variable of type G<T>.

Structs S1, S2, S3 are implemented while conforming to protocol P.

With types defined above I have also written resolver functions.

```swift
func resolve(_ arg: some P) -> some P {
    switch arg {
    case is S1: print("S1")
    case is S2: print("S2")
    case is S3: print("S3")
    default: print("any P")
    }
    return arg
}

func resolveExistential<U:P>(_ arg: U) -> G<U.T> {
    return arg.generic
}
```

And following is the actual problem I encountered.

```swift
let list: [any P] = [S1(), S2(), S3()]

list.forEach {
    print($0.value)                         // OK
    print($0.generic.wrappedValue)          // Not OK, Member 'generic' cannot be used on value of type 'any P'; consider using a generic constraint instead
    print(resolve($0))                      // OK
    print(resolveExistential($0))           // Not OK, Type 'any P' cannot conform to 'P'
}
```

Is there a way to resolve or directly access $0.generic?

**Comment by jamieQ** [comment]
I'm not entirely sure, but I believe the issue stems from the type-erasure rules that apply in these cases. I think the relevant bit from the implicitly-opened existentials proposal is [here](https://github.com/apple/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md#type-erasing-resulting-values), which states:

> When T or a T-rooted associated type appears in a non-covariant position in the result type, T cannot be bound to the underlying type of an existential value because there would be no way to represent the type-erased result. This is essentially the same property as descibed for the parameter types that prevents opening of existentials, as described above. For example:
> ```swift
> func cannotOpen7<T: P>(_ value: T) -> X<T> { /*...*/ }
>```

[This](https://forums.swift.org/t/type-any-protocol-cannot-conform-to-protocol/59266) seemed to be a related question on the Swift forums, which might be of interest. I believe this case is analogous to the one posed in that post, and the issue is that the return type of your `resolveExistential` function uses the binding to the opened existential value in a 'non-covariant position' (i.e. as a generic parameter of the function's return type).

**Comment by heecheon92** [comment]
@jamieQ 

Thanks for the reference. I will just close this issue as there doesn't seem to be any viable workaround.

**Comment by jamieQ** [comment]
FWIW, depending on the use case, you may still be able to do something with the underlying generic property. I think the core issue in your example is returning the generic value. If your `resolveExistential` function were changed to something like this:

```swift
func resolveExistentialNoReturn<U:P>(_ arg: U) {
    print("U.G<T>: \(arg.generic)")
}
```

then I think the implicit existential opening will work.
