### ISSUE TITLE
Lexer bleeds into parser

### ISSUE THREAD

**Issue by za-creature** [apple/swift#67968]
Not sure if this is a bug, but it got me wondering

![Screenshot 2023-08-16 at 23 11 47](https://github.com/apple/swift/assets/1210845/f5244ba0-004c-4485-869b-7a8eb95a3299)

**Comment by za-creature** [comment]
```swift
    @inline(__always) func assertRange(_ id: Int64) { ... }
```

same error when replacing `assertRange` with `print`, Xcode 14.3.1 (14E300c)

**Comment by tbkka** [comment]
Looks reasonable to me:
```
assertRange(after & (Self.SENT -1))
```
The token `-1` is a number, not a subtraction operator followed by a `1`.  So the early parser has to make some guess in order to proceed.  In this case, it guesses that you meant `(Self.SENT, -1)` which is a valid tuple.

Then the type checker looks at it and can't make sense of the result: 
* the argument to `assertRange` has to be Int64, so
* `&` must be the bitwise AND operator on Int64, so
* `after` must be Int64 (already is, I presume), and
* `(Self.SENT, -1)` must also be Int64, which generates the error here.

So this is indeed "not a bug" in the compiler in the sense that it's invalid code and the compiler is rejecting it.  But you could argue that a clearer error in this specific case would suggest to the user that they might have meant `- 1` (with a space between `-` and `1` instead of `-1`).

The questions are:
* How complex would it be to detect cases of this sort and issue more appropriate errors?
* Would that cause there to be less clear errors in any other cases?

**Comment by za-creature** [comment]
Hey Tim!

Apologies for not writing a better error report and yes, most of your assumptions are correct minus the last one where the compiler induced a comma where there was none (not a bug imo).

My take on it is that this is somewhat related to:

![Screenshot 2023-08-17 at 00 07 46](https://github.com/apple/swift/assets/1210845/a201a07c-ba1d-407a-a3dc-1aa6eee9ae06)

While I strongly agree that operator spacing should be consistent, what I really wanted to report was that not only is there a different error message between the scenarios, it's also a different **type** of error:
* the `lexer` (i.e. early parser a.k.a. the thing you use to translate characters into tokens) is the one that complains about the missing comma (IIRC an earlier version of swift would explicitly state that spacing should be consistent but the error message is not the issue here)
* the parser (a.k.a. the compiler proper that has an understanding of types) is the one that complains about the type mismatch

To my (admittedly limited) understanding of compilers, this syntax error (if Swift enforces my opinion on operator consistency) should stop the compilation _before_ it reaches the stage that is aware of types (what I call the `parser`). The fact that it doesn't is the key issue here.

If this is intended (e.g. swift is either context-sensitive, or runs a context-free first pass and then a context-sensitive pass in order to provide better error messages) then this is probably not a bug and you can close it with confirmation thereof.

**Comment by tbkka** [comment]
Swift does run multiple passes with different analysis capabilities to provide better errors in different scenarios.  Different kinds of errors can be detected and emitted by the lexer, the parser, the type checker, the generics system, the diagnostics system, or the optimizer.  Each of those has different information to work from and can detect different kinds of problems.  And especially when working in an IDE like Xcode, most users find it convenient to run as much of the compiler as we can to detect as many kinds of errors as possible, which is why many of the compiler phases try to fill in guesses to allow other phases to make progress.
