### ISSUE TITLE
`bridgedSourceLoc` should be a member on `SyntaxProtocol`

### ISSUE THREAD

**Issue by ahoppen** [apple/swift#68354]
We have changed the paradigm to prefer passing `ASTGenVisitor` as a parameter to eg. `Collection.map(in:)` rather than defining a function on `ASTGenVisitor` that takes an argument because it puts the subject of the operation at the start, which reads nicer.

To stick with that paradigm, `ASTGenVisitor.bridgedSourceLoc(for node: (some SyntaxProtocol)?)` should become

```swift
extension SyntaxProtocol {
  func bridgedSourceLoc(in astgen: ASTGenVisitor) { … }
}
```

**Comment by mininny** [comment]
I'm not sure if it's okay for me to work on this, but it didn't look so complicated so I created a test PR for the poc https://github.com/apple/swift/pull/68460

Before I can expand the change to the whole `bridgeSourceLoc` usages, could you please take a look at it and provide some guidance if it's the right direction that this issue is trying to resolve?
