### ISSUE TITLE
Static methods added via ExtensionMacro not visible outside file where macro was applied

### ISSUE THREAD

**Issue by matthewcheok** [apple/swift#69013]
**Description**

When accessing a static member of an extension (added via `ExtensionMacro`) outside the file that it is applied in, we get the following error `Error: Type 'any Foo' has no member 'default`. Access should be allowed outside the file it is applied (within the same module, if internal)

**Steps to reproduce**

Sample project: [DefaultProviding.zip](https://github.com/apple/swift/files/12830467/DefaultProviding.zip)
- Verify access is allowed in `Foo.swift`
```
// Testing accessing `.default()` in `Foo.swift`
let t: Foo = .default() // OK
```

- Verify that access is not allowed in `main.swift`
```
// Testing accessing `.default()` in `main.swift`
let m: Foo = .default() // Error: Type 'any Foo' has no member 'default
```

**Expected behavior**

Code should compile without errors.

**Environment**
- Swift compiler version info 
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
- Xcode version info 
Xcode 15.0
- Deployment target: 
iOS 17/macOS Sonoma

**Comment by SixthDot** [comment]
IS this a dup of #68515 ?

**Comment by xedin** [comment]
This is indeed similar to https://github.com/apple/swift/issues/68515 and fix I mentioned there resolved the issue with `.default` reference. There is another problem here related to the macro itself - `defaultProviding` is applied to `Foo` and mentions `Bar` - that is circular because `Bar` conforms to `Foo` which means that we cannot resolve `Foo` fully without `Bar` and vice versa. Please use Trunk Development snapshot from swift.org to verify and I'm going to close this issue since the compiler issue has been fixed.
