### ISSUE TITLE
Passing nil to a parameter pack fails to produce diagnostic for expression

### ISSUE THREAD

**Issue by alimyuz** [apple/swift#69432]
**Description**
Passing nil to a parameter pack fails to produce diagnostic for expression. This of course is invalid code but a good diagnostic would be nice to have.

**Steps to reproduce**
```swift
func foo<each T>(_ bar: repeat each T) { }

foo(nil) // Failed to produce diagnostic for expression; please submit a bug report
```

**Expected behavior**
Build error with appropriate diagnostic.

**Environment**
- Swift compiler version info
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1) 
Target: arm64-apple-macosx14.0
- Xcode version info
Xcode 15.0.1
Build version 15A507
- Deployment target:
macOS 14.0

**Comment by xedin** [comment]
I think this is a good first issue. What needs to be done is to teach `TypeVariableBinding::fixForHole` about `pack element` location and produce `DefaultGenericArgument` fix.

**Comment by AlexFarmer3** [comment]
I am looking to get started contributing to Swift, and I think this looks like a good first issue for me! May I please be assigned to this issue?

**Comment by xedin** [comment]
Absolutely!

**Comment by Rajveer100** [comment]
@AlexFarmer3 
Are you working on this?

**Comment by Rajveer100** [comment]
@xedin 
I see a method `isParameterPack` in `TypeVariableBinding::fixForHole` and also seem to have found places where a `DefaultGenericArgument` is created which takes a few `parameters`.

But how do we check for the same? 

In my finding there is `dstLocator`, `srcLocator` and a `TypeVar`, could you elaborate a bit on this?

**Comment by xedin** [comment]
This is a situation very similar to:

```
func test<T>(_: T) {}

test(nil)
```

I actually wonder whether disallowing type variables that represent pack elements to be bound to holes is going to fix this issue (because `nil` when bound to hole _directly_ would already produce `SpecifyContextualTypeForNil` fix). To make that happen you need to figure out where a new type variable that points to `LocatorPathElt::PackElement` is created and remove `TVO_CanBindToHole` flag from it (plus make sure that all other cases still work).

Other way of approaching this would be in `TypeVariableBinding::fixForHole` to check whether `TypeVar`'s locator ends with `PackElement` and if so either:

a. Create and record a new fix that is going to produce a diagnostic similar to `type of pack expansion 'each T' cannot be inferred'`. 
b. Teach existing DefaultGenericArgument fix to handle pack elements instead of only generic parameter declarations (this is going to be harder and maybe not worth the effort to avoid adding a new fix).

I'd suggest checking whether disallowing binding to holes works first.

**Comment by Rajveer100** [comment]
> To make that happen you need to figure out where a new type variable that points to LocatorPathElt::PackElement is created and remove TVO_CanBindToHole flag from it (plus make sure that all other cases still work).

I do see the `TVO_CanBindToHole` flag, where a `freshTypeVar` is being created when the `packExpansionElt` exists, so by removing you meant to always pass `0` (`false`), whether or not `canBindToHole` is possible?

If that's the case, compiler still fails to produce diagnostic for expression.

> a. Create and record a new fix that is going to produce a diagnostic similar to type of pack expansion 'each T' cannot be inferred'.

I think I can then create a new diagnostic as you mentioned.

**Comment by Rajveer100** [comment]
For the `DefaultGenericArgument` fix, what do we pass for `GenericTypeParamType`? Also, when calling a new fix, we generally do it using `diag::` right, how would the compiler know about this new diagnostic message that we create, i.e, what's the appropriate location to call `diag::<diagnostic_message>` once this fix is passed via `fixForHole?`
