### ISSUE TITLE
`withUnsafeContinuation` doesn't inherit Actor executor during single await call

### ISSUE THREAD

**Issue by kntkymt** [apple/swift#69659]
**Description**

Encountered a failure with `MainActor.shared.assertIsolated()` in the following code:

```swift
@MainActor
func doSomething() async {
    await withUnsafeContinuation { continuation in
        if #available(macOS 14.0, *) {
            MainActor.shared.assertIsolated()
        }

        continuation.resume(returning: ())
    }
}

await Task.detached {
    await doSomething()
}.value
```

**Expected behavior**

The `MainActor.shared.assertIsolated()` call should not fail.

**Environment**

- Swift compiler version info: swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
- Xcode version info: Xcode 15.0.1 Build version 15A507
- Deployment target: arm64-apple-macosx14.0

**Issue Details**

I suspect that the optimization which omits `hop_to_executor` during single await call does not account for `_unsafeInheritExecutor`.

This problem only appear when `doSomething` has single await call. The following code does work.

```swift
@MainActor
func doSomething() async {
    print("Hello") // write something
    await withUnsafeContinuation { continuation in
        if #available(macOS 14.0, *) {
            MainActor.shared.assertIsolated()
        }

        continuation.resume(returning: ())
    }
}

await Task.detached {
    await doSomething()
}.value
```

When the MainActor isolated async function (funcA) has only single await call (funcB),
we doesn't need hop to MainActor executor before calling funcB because hop to general executor when calling funcB.
However, when funcB has `_unsafeInheritExecutor`, we need hop to MainActor executor before calling it.

Inspecting the SIL, it seems that hop to MainActor has been erroneously removed by the optimization process.

SIL outputs here:
https://gist.github.com/kntkymt/3f8af33b98f238128a0eba638b74b81d

**Comment by kntkymt** [comment]
When we fixed the Future Direction of this proposal SE-0420, this will became easier to fix this problem.

https://github.com/apple/swift-evolution/blob/main/proposals/0420-inheritance-of-actor-isolation.md#future-directions

**Comment by kntkymt** [comment]
https://github.com/apple/swift/issues/69659#issuecomment-2016702650

Oh, I found This approarch will not solve this problem, because we hop to the global pull when entering the continuation closure.

**Comment by ktoso** [comment]
We looked at this with @kntkymt during the try swift hackathon, and the issue is that even if we fixed the isolation of the `withUnsafeContination` there appears to be an executor switch:

```
@MainActor
@available(SwiftStdlib 9999, *)
func doSomething() async {
  MainActor.shared.assertIsolated() // OK

  await FIX_withUnsafeContinuation(isolation: MainActor.shared) { continuation in
    MainActor.shared.assertIsolated() // BOOM
    continuation.resume(returning: ())
  }
```

```
[Actor.cpp:150](enterAndShadow) CHANGE TO: 0x1de8f69c0
[Actor.cpp:150](enterAndShadow) CHANGE TO: 0x0
[Actor.cpp:150](enterAndShadow) CHANGE TO: 0x1de8f69c0
[Actor.cpp:345](swift_task_isCurrentExecutorImpl) expected executor: 0x1de8f69c0
[Actor.cpp:347](swift_task_isCurrentExecutorImpl) current executor: 0x1de8f69c0
[Actor.cpp:150](enterAndShadow) CHANGE TO: 0x0
[Actor.cpp:345](swift_task_isCurrentExecutorImpl) expected executor: 0x1de8f69c0
[Actor.cpp:347](swift_task_isCurrentExecutorImpl) current executor: 0x0
Incorrect actor executor assumption; Expected MainActor executorProcess 94325 stopped
```

The change to 0x0, global pool is unexpected here; and there is no `hop_to_executor` off the main actor in the SIL but we do seem to change the executor so that's a bit confusing what's going on there.

I wonder if we should make the builtin accept an isolation, or make the 
```
@available(SwiftStdlib 5.1, *)
// @_unsafeInheritExecutor // replace with isolation 
@_alwaysEmitIntoClient
public func withUnsafeContinuation<T>(
  _ fn: (UnsafeContinuation<T, Never>) -> Void,
  isolation: (any Actor)? = #isolation
) async -> T {
  return await Builtin.withUnsafeContinuation { // todo, make sure to isolate to the isolation here
    fn(UnsafeContinuation<T, Never>($0))
  }
}
```

to avoid the issue? It's surprising though why we enter `enterAndShadow` with the global executor, so that's what we need to fix here.

**Comment by rjmccall** [comment]
I've been thinking about making the builtin take an executor so that we can resume the task on the right isolation.  But I don't think that has anything to do with the problem here, because that only happens after the task is resumed, i.e. on the edge out of the callback.

It does sound like we're optimizing away the `switch` before the call, which is problematic.  Is the code snippet above the implementation of `withUnsafeContinuation` you were using for `FIX_withUnsafeContinuation`?  Because you've forgotten to actually make the parameter `isolated`.

**Comment by ktoso** [comment]
That's silly -- indeed I missed to add the `isolated` and that seems to resolve the issue.

We could do that right away I think if we wanted to
