### ISSUE TITLE
Should the compiler warn about a type that is both globally-isolated and Sendable?

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#71473]
### Motivation

Something I'm noticing people do is both mark a class MainActor *and also* make it Sendable. I don't see why this should be allowed - it seems like a logical mistake. The developer is simultaneous expressing that this type is both only usable on one actor and also safe to pass to any actor.

I don't know if an error is appropriate but maybe a warning? 

```swift
@MainActor
class MyClass: Sendable {}
```

### Proposed solution

I think this should produce a warning.

**Comment by hborla** [comment]
>Something I'm noticing people do is both mark a class MainActor and also make it Sendable. I don't see why this should be allowed - it seems like a logical mistake.

Hmm, can you please elaborate on why you think this is the case? Making a class isolated to the `@MainActor` implies a conformance to `Sendable`. You can pass an instance of the value across isolation boundaries and have concurrent references to it specifically because its state is protected by actor isolation -- to touch any state, you need to get back on the main actor. You can still call any `nonisolated` methods on the class because those cannot touch main actor isolated state. The `Sendable` conformance is just being explicit, but a `Sendable` conformance is inferred if you don't write it!

**Comment by mattmassicotte** [comment]
I think I can chock this up to just misunderstanding on my part. Sorry for the noise!
