### ISSUE TITLE
using `is AnyObject` to test a value type, But it returns true.

### ISSUE THREAD

**Issue by carlhung** [apple/swift#72223]
### Description

using `is AnyObject` to test a value type, But it returns true.

### Reproduction

```swift
func foo(_ val: Any) -> Bool {
    val is AnyObject
}

let x = 0
print(foo(x)) // true

```

### Expected behavior

expecting to return false.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by tbkka** [comment]
This is expected behavior.

In order to facilitate interoperability with Objective-C, Swift allows _any_ object at all to be converted to a reference-counted pointer through dynamic casting.  If the object is a class object, this is trivial; otherwise, the object will be copied to a heap-allocated box.  "Dynamic casting" includes `is`, `as?`, and `as!` operations.  In fact, `is` is actually defined as
```
val is Type ⇔ (val as? Type) != nil
```
It might help to read `val is Type` as "val can be converted to Type".
