### ISSUE TITLE
Protocol existentials do not trigger warnings if they will never be executed 

### ISSUE THREAD

**Issue by chrisballinger** [apple/swift#73649]
### Description

Early returns do not trigger warnings for protocol existentials, see example below

### Reproduction

```swift
protocol SomeProtocol {
    func doTheThing()
}

func output(someProtocol: SomeProtocol) -> String {
    return "test"
    someProtocol.doTheThing() // this should be a warning
}
```

### Expected behavior

early return should cause a compiler warning on the code that will never be executed

### Environment

$ swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

### Additional information

using a generic brings the warning back, e.g.

```swift
func output(someProtocol: some SomeProtocol) -> String {
    return "test"
    someProtocol.doTheThing() // this shows a warning
}
```

**Comment by jamieQ** [comment]
looked into this a bit out of curiosity. it seems to me likely that this behavior is due to hitting [this branch](https://github.com/apple/swift/blob/2c6bfa23c8432b54c6a247f92536239beeac3c9a/lib/SILGen/SILGenStmt.cpp#L371-L373) in the SILGen code. it appears that, by default, diagnosing 'implicit' expressions (i.e. those that are not explicitly-written in source code) is suppressed, but there are a handful of carve-outs for things that should be exempted from this rule (e.g. [optional chaining](https://github.com/apple/swift/blob/2c6bfa23c8432b54c6a247f92536239beeac3c9a/lib/SILGen/SILGenStmt.cpp#L359-L365)). in the reproduction, the relevant portion of the AST is something like:

```md
(open_existential_expr implicit type='()' location=/app/example.swift:12:18 range=[/app/example.swift:12:5 - line:12:29]
  (opaque_value_expr implicit type='any SomeProtocol' location=/app/example.swift:12:5 range=[/app/example.swift:12:5 - line:12:5] @ 0x5a20baa22810)
  (declref_expr type='any SomeProtocol' location=/app/example.swift:12:5 range=[/app/example.swift:12:5 - line:12:5] decl=output.(file).output(someProtocol:maybeSP:someClass:).someProtocol@/app/example.swift:9:13 function_ref=unapplied)
  (call_expr type='()' location=/app/example.swift:12:18 range=[/app/example.swift:12:5 - line:12:29] nothrow isolationCrossing=none
    (dot_syntax_call_expr type='() -> ()' location=/app/example.swift:12:18 range=[/app/example.swift:12:5 - line:12:18] nothrow isolationCrossing=none
      (declref_expr type='(any SomeProtocol) -> () -> ()' location=/app/example.swift:12:18 range=[/app/example.swift:12:18 - line:12:18] decl=output.(file).SomeProtocol.doTheThing()@/app/example.swift:2:10 [with (substitution_map generic_signature=<Self where Self : SomeProtocol> (substitution Self -> @opened("7A730076-1388-11EF-ABE0-81AF1B259855", any SomeProtocol) Self))] function_ref=single)
      (argument_list implicit
        (argument
          (opaque_value_expr implicit type='any SomeProtocol' location=/app/example.swift:12:5 range=[/app/example.swift:12:5 - line:12:5] @ 0x5a20baa22810))))
    (argument_list))))))
```

so i'd assume adding some special handling for that particular structure (i.e. [`OpenExistentialExpr`](https://github.com/apple/swift/blob/dfba6e2d7379fb8a9de210ad6b8ba970c863bd0f/include/swift/AST/Expr.h#L2862)), as is done for the optional chaining case, would likely be one way to address the issue. or perhaps there's a way to generalize what the special cases have in common, e.g. a top-level implicit expression which internally contains a non-implicit expression that should be diagnosed.
